# Generated by Django 5.2.7 on 2026-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("clinic", "Clinic"),
                            ("hr", "HR"),
                            ("guidance", "Guidance"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send reports to for this department",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Contact",
                "verbose_name_plural": "Notification Contacts",
                "db_table": "notification_contact",
            },
        ),
    ]
