# Generated by Django 5.2.7 on 2026-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("College", models.CharField(max_length=255)),
                ("User_Type", models.CharField(max_length=255)),
                ("Month", models.CharField(max_length=255)),
                ("Day", models.IntegerField(max_length=255)),
                ("Year", models.IntegerField(max_length=255)),
                ("EmployeeID_or_Guest", models.CharField(max_length=255)),
                ("Body_Temperature_C", models.FloatField(max_length=255)),
                ("Blood_Pressure", models.CharField(max_length=255)),
                ("Systolic_BP", models.IntegerField(max_length=255)),
                ("Diastolic_BP", models.IntegerField(max_length=255)),
                ("Heart_Rate_bpm", models.IntegerField(max_length=255)),
                ("Emotion", models.CharField(max_length=255)),
                ("Risk_Level", models.CharField(max_length=255)),
                ("Alert_Status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("College", models.CharField(max_length=255)),
                ("Course", models.CharField(max_length=255)),
                ("Year_Level", models.IntegerField(max_length=255)),
                ("Month", models.CharField(max_length=255)),
                ("Day", models.IntegerField(max_length=255)),
                ("Year", models.IntegerField(max_length=255)),
                ("StudentID", models.IntegerField(max_length=255)),
                ("Body_Temperature_C", models.FloatField(max_length=255)),
                ("Blood_Pressure", models.CharField(max_length=255)),
                ("Heart_Rate_bpm", models.IntegerField(max_length=255)),
                ("Emotion", models.CharField(max_length=255)),
            ],
        ),
    ]
