# Generated by Django 5.2.7 on 2026-05-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitalwatch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyrecord",
            name="Day",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="facultyrecord",
            name="Diastolic_BP",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="facultyrecord",
            name="Heart_Rate_bpm",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="facultyrecord",
            name="Systolic_BP",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="facultyrecord",
            name="Year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="Day",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="Heart_Rate_bpm",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="StudentID",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="Year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="Year_Level",
            field=models.IntegerField(),
        ),
    ]
