# Generated by Django 5.2.7 on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitalwatch", "0002_alter_facultyrecord_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrecord",
            name="StudentID",
            field=models.CharField(max_length=255),
        ),
    ]
